# ==========================================
# 📚 CATÁLOGO DE CONSULTAS SQL
# ==========================================

BIBLIOTECA_SQL = {
    "Selecione uma consulta pronta...": "",
    "Tanque de Compra": """
SELECT NOMEMARCA, CNPJFORNECEDOR, COUNT(HANDLE)
FROM K9_TQ_LISTAPRECOS
GROUP BY NOMEMARCA,CNPJFORNECEDOR;
    """.strip(),
    "Tanque de Venda": """
SELECT GP.APELIDO,F.NOMEFANTASIA,FV.STATUS,FV.LISTAPRECOCOMPRA, FV.MENSAGEM, E.SIGLA  FROM K9_TQ_FORMARPRECOVENDA FV
JOIN  GN_PESSOAS GP ON GP.HANDLE = FV.FORNECEDOR
JOIN FILIAIS F ON F.HANDLE = FV.FILIALGERAR
JOIN ESTADOS E ON E.HANDLE = FV.ESTADOGERAR
GROUP BY GP.APELIDO,F.NOMEFANTASIA,FV.STATUS,FV.LISTAPRECOCOMPRA, FV.MENSAGEM , E.SIGLA
ORDER BY STATUS DESC, GP.APELIDO,F.NOMEFANTASIA;
    """.strip(),
    "Vigência Listas de Preço": """
SELECT LP.HANDLE, GP.APELIDO , LP.VIGENCIAINICIAL, LP.VIGENCIAFINAL 
FROM K9_CP_LISTAPRECOS LP
JOIN GN_PESSOAS GP ON GP.HANDLE = LP.FORNECEDOR
WHERE VIGENCIAFINAL >= GETDATE()
AND VIGENCIAFINAL <> '9999-12-31 00:00:00'
    """.strip(),
    "Marcas": """
SELECT PM.NOME FROM PD_MARCASPRODUTOS PM
WHERE PM.EHITEM = 'S'
    """.strip()
}