consultas_rapidas_benner = {
    "Selecione uma consulta pronta...": "",
    "Tanque de Compra": """
SELECT NOMEMARCA, CNPJFORNECEDOR, COUNT(HANDLE)
FROM K9_TQ_LISTAPRECOS
GROUP BY NOMEMARCA,CNPJFORNECEDOR;
    """.strip(),
    "Tanque de Venda": """
SELECT GP.APELIDO,F.NOMEFANTASIA,FV.STATUS,FV.LISTAPRECOCOMPRA, FV.MENSAGEM, E.SIGLA  FROM K9_TQ_FORMARPRECOVENDA FV
JOIN  GN_PESSOAS GP ON GP.HANDLE = FV.FORNECEDOR
JOIN FILIAIS F ON F.HANDLE = FV.FILIALGERAR
JOIN ESTADOS E ON E.HANDLE = FV.ESTADOGERAR
GROUP BY GP.APELIDO,F.NOMEFANTASIA,FV.STATUS,FV.LISTAPRECOCOMPRA, FV.MENSAGEM , E.SIGLA
ORDER BY STATUS DESC, GP.APELIDO,F.NOMEFANTASIA;
    """.strip(),
    "Vigência Listas de Preço": """
SELECT LP.HANDLE, GP.APELIDO , LP.VIGENCIAINICIAL, LP.VIGENCIAFINAL 
FROM K9_CP_LISTAPRECOS LP
JOIN GN_PESSOAS GP ON GP.HANDLE = LP.FORNECEDOR
WHERE VIGENCIAFINAL >= GETDATE()
AND VIGENCIAFINAL <> '9999-12-31 00:00:00'
    """.strip(),
    "Marcas": """
SELECT DISTINCT M.HANDLE,
M.NOME AS MARCA
FROM PD_PRODUTOSPAI P
JOIN PD_MARCASPRODUTOS M ON M.HANDLE = P.MARCAPRODUTO
JOIN PD_PRODUTOS PP ON P.CODIGO = PP.CODIGO
JOIN FILIAIS F ON PP.FILIAL = F.HANDLE
WHERE 1 =1
    AND P.ATIVO = 'S'
    AND P.K_DESCONTINUADO = 'N'
    AND M.EHITEM = 'S'
    AND F.HANDLE IN (3, 8, 10, 11, 12, 14, 16, 18, 19, 20, 38, 322)
GROUP BY M.HANDLE, M.NOME
;
    """.strip()
}