SQL_MARCAS_ATIVAS = """
SELECT DISTINCT M.NOME AS MARCA
FROM PD_PRODUTOSPAI P
JOIN PD_MARCASPRODUTOS M ON M.HANDLE = P.MARCAPRODUTO
JOIN PD_PRODUTOS PP ON P.CODIGO = PP.CODIGO
WHERE 1 =1
    AND P.ATIVO = 'S'
    AND P.K_DESCONTINUADO = 'N'
    AND M.EHITEM = 'S'
GROUP BY M.NOME
ORDER BY M.NOME
;
""".strip()

SQL_TANQUE_COMPRA = """
SELECT NOMEMARCA, CNPJFORNECEDOR, COUNT(HANDLE)
FROM K9_TQ_LISTAPRECOS
GROUP BY NOMEMARCA,CNPJFORNECEDOR;
""".strip()

SQL_TANQUE_VENDA = """
SELECT GP.APELIDO,F.NOMEFANTASIA,FV.STATUS,FV.LISTAPRECOCOMPRA, FV.MENSAGEM, E.SIGLA  FROM K9_TQ_FORMARPRECOVENDA FV
JOIN  GN_PESSOAS GP ON GP.HANDLE = FV.FORNECEDOR
JOIN FILIAIS F ON F.HANDLE = FV.FILIALGERAR
JOIN ESTADOS E ON E.HANDLE = FV.ESTADOGERAR
GROUP BY GP.APELIDO,F.NOMEFANTASIA,FV.STATUS,FV.LISTAPRECOCOMPRA, FV.MENSAGEM , E.SIGLA
ORDER BY STATUS DESC, GP.APELIDO,F.NOMEFANTASIA;
""".strip()

SQL_VIGENCIA_LISTAS = """
SELECT LP.HANDLE, GP.APELIDO , LP.VIGENCIAINICIAL, LP.VIGENCIAFINAL 
FROM K9_CP_LISTAPRECOS LP
JOIN GN_PESSOAS GP ON GP.HANDLE = LP.FORNECEDOR
WHERE VIGENCIAFINAL >= GETDATE()
AND VIGENCIAFINAL <> '9999-12-31 00:00:00'
""".strip()

# INTERFACE
MENU_CONSULTAS_RAPIDAS = {
    "Tanque de Compra": SQL_TANQUE_COMPRA,
    "Tanque de Venda": SQL_TANQUE_VENDA,
    "Vigência Listas de Preço": SQL_VIGENCIA_LISTAS,
    "Marcas": SQL_MARCAS_ATIVAS
}